import type { AgentName } from "./types.js";

export const WORKFLOW_MARKER = "OFLOW MANAGED BLOCK";
export const CACHE_POLICY_MARKER = "OFLOW CACHE POLICY";

export const CACHE_POLICY_MARKDOWN = [
  "## Mandatory cache policy",
  "",
  "Agents must follow this refresh policy:",
  "",
  "1. At the start of a work session, run `oflow work --mine --refresh --json` and `oflow sync --summary --refresh --json`.",
  "2. During exploration and repeated context reads, use `oflow work --mine --cached --json` and `oflow sync --summary --cached --json`.",
  "3. Before planning, approving, applying, or verifying a remote GitLab change, refresh current state; never treat cached data as remote truth.",
  "4. If refresh fails, continue local analysis only and do not apply a remote mutation.",
  "5. After applying a remote change, refresh the work and project snapshots again.",
  "6. Use `oflow context --story <iid>` and `oflow assess --story <iid> --json` for detailed story and acceptance-criteria evidence.",
  "7. Use `oflow dashboard` for a local read-only view; it binds to 127.0.0.1 and never sends GitLab credentials to the browser.",
  "",
  "Cached reads never contact GitLab. They are a local read model, not a freshness guarantee.",
].join("\n");

const CACHE_POLICY_MANAGED_BLOCK = [
  "<!-- BEGIN " + CACHE_POLICY_MARKER + " -->",
  CACHE_POLICY_MARKDOWN,
  "<!-- END " + CACHE_POLICY_MARKER + " -->",
].join("\n");

export const WORKFLOW_MARKDOWN = [
  "# oflow workflow",
  "",
  "This project uses oflow as its GitLab-first agent workflow contract.",
  "",
  "## Before starting",
  "",
  "1. Read this file, the story context, and the relevant local code.",
  "2. If no story is known, run oflow work to inspect open GitLab work items.",
  "3. Resolve the active story with oflow start --story <iid> or the branch naming convention.",
  "4. Run oflow context --story <iid> and preserve the story's acceptance criterion IDs.",
  "5. If GitLab access is missing, run oflow auth login; never put tokens in this repository. During setup or troubleshooting, use oflow doctor --check-api --json for bounded read diagnostics; it never probes writes.",
  "6. When asked to sync project state, run oflow sync --summary --json for the token-light overview. Use oflow sync --json only when full bounded planning collections or pagination are needed. Use oflow sync --cached --summary --json for repeated context when the last snapshot is acceptable, and --refresh when current GitLab state is required. For repeated assigned-work context, use oflow work --mine --cached after an initial oflow work --mine --refresh; cached reads never contact GitLab. Add --epics only when group-level epic context is needed; it costs one extra bounded GraphQL read. When assessing one story, run oflow assess --story <iid> --json and use oflow capabilities --json to discover supported operations.",
  "8. State the plan and identify anything ambiguous before making code changes.",
  "",
  CACHE_POLICY_MANAGED_BLOCK,
  "",
  "## While working",
  "",
  "- Treat the GitLab story and its acceptance criteria as the source of truth.",
  "- Do not silently change acceptance criteria; ask the user or record the clarification in GitLab.",
  "- Keep implementation, tests, and documentation aligned.",
  "- Keep secrets and local .oflow/state/ files out of commits.",
  "- Refresh context when the story, MR, pipeline, or user direction changes.",
  "- Treat oflow sync as evidence collection; do not infer completion without concrete local or GitLab evidence.",
  "- In assess JSON, localReferences are advisory pointers only; inspect the referenced code/test and never treat an ID match as acceptance proof.",
  "- Verify pipeline evidence belongs to the selected MR and matches its head SHA when GitLab provides one; a branch pipeline alone is not enough.",
  "- The dashboard is local-only. Its refresh control records a request; run `oflow sync --refresh` explicitly to contact GitLab.",
  "",
  "## Before handoff",
  "",
  "1. Update the MR description with one checklist item for every AC-n criterion.",
  "2. Add concrete, non-placeholder Evidence: for every checked criterion.",
  "3. Run the relevant tests and describe their result as evidence.",
  "4. Run oflow verify --story <iid>.",
  "5. Report changed files, checks run, remaining risks, and the GitLab links.",
  "",
  "## Safety",
  "",
  "Read-only context, sync, and verification commands may run automatically.",
  "Use work/sync filters (--label, --milestone, --iteration, --epic, --assignee,",
  "--author, --search, --updated-after, --updated-before, --limit) when a smaller server-side snapshot is enough.",
  "Treat pagination.hasNextPage as evidence that a bounded collection needs a narrower filter or a larger limit.",
  "oflow does not configure or invoke MCP servers. Use plan assess --story <iid> --assignee <username> --milestone <title> when the assessment has a confirmed owner/timebox, or use plan issue update (including",
  "--labels for replacement or --add-labels/--remove-labels to preserve unrelated labels,",
  "--assignee username or --epic <id|none> or --iteration <title|iid|none>), plan issues labels --stories <iid,...> for",
  "bounded multi-story label changes, plan issues update --stories <iid,...> for",
  "bounded owner/timebox or --iteration changes, plan issue create/note, or",
  "plan label/milestone/board/board-list create/update, then approve, apply, and verify for supported writes. Do not",
  "use planned commands until oflow capabilities reports them as supported.",
].join("\n");

export const OFLOW_README_MARKDOWN = [
  "# .oflow",
  "",
  "This directory is the project-local configuration for oflow.",
  "",
  "- config.json records the GitLab remote and detected agent mode.",
  "- WORKFLOW.md is the shared agent workflow contract.",
  "- templates/merge-request.md is the acceptance-aware MR template.",
  "- GitLab credentials live outside the repository; use oflow auth login.",
  "- oflow reads GitLab through its typed REST API; explicit group-epic reads use GraphQL, while glab and MCP remain optional integrations.",
  "- oflow glab api <GET endpoint> is an explicit GET-only fallback for unwrapped endpoints.",
  "- Use work/sync filters, --limit, and sync --stale-days when an explicit age threshold is useful to keep planning context focused.",
  "- Live sync and work reads write credential-free ignored caches; sync --cached and work --cached never contact GitLab and report snapshot age. Refresh before relying on current state or preparing a remote write.",
  "- Mandatory cache policy: refresh at session start, use cached reads during exploration, refresh before remote changes, stop remote mutations if refresh fails, and refresh again after applying changes.",
  "- In sync JSON, check pagination.hasNextPage before treating a collection as complete.",
  "- Use oflow audit --json to inspect local plan lifecycle history; it never contacts GitLab or contains tokens.",
  "- Use plan issues labels --stories <iid,...> for bounded multi-story workflow-label changes.",
  "- Use oflow audit --json to review local plan lifecycle history without contacting GitLab.",
  "- state/ and cache/ are local and ignored; cache/oflow.db is the local SQLite read model and may contain project context but never credentials.",
  "- oflow doctor --check-api --json reports bounded REST/GraphQL read probes, optional backend status, and write capabilities as not-probed; it never mutates GitLab.",
  "- Scrum/planning: work items, acceptance criteria, labels, boards, milestones, iterations, group epics, MRs, and pipelines.",
  "- GitHub Copilot and VS Code agents can use .github/copilot-instructions.md and this same CLI JSON contract.",
  "- Run oflow cache status --json for local cache age/schema/invalidation diagnostics, and oflow dashboard for the loopback-only browser view.",
  "",
    "Run oflow doctor --check-api --json to inspect setup and bounded API access, oflow sync",
    "--summary --json for a token-light overview, oflow sync --json for the full bounded snapshot, oflow sync --cached --json for a no-network repeat read, oflow iteration --state current --json for a focused sprint view, oflow cadence --json for the optional parent-group cadence, or oflow assess --story <iid> --json for",
  "compact progress evidence for one story.",
].join("\n");

export const MERGE_REQUEST_TEMPLATE_MARKDOWN = [
  "# Summary",
  "",
  "## Story",
  "",
  "Closes #<story-iid>",
  "",
  "## Acceptance criteria verification",
  "",
  "- [ ] AC-1: <copy the exact criterion text>",
  "  Evidence: TBD",
  "",
  "<Repeat one checked item and one concrete Evidence: line for every criterion.>",
  "",
  "## Implementation notes",
  "",
  "- What changed?",
  "- What tests or other verification were run?",
  "- What remains or needs follow-up?",
].join("\n");

export const COPILOT_INSTRUCTIONS_MARKDOWN = [
  "# oflow instructions for GitHub Copilot and VS Code agents",
  "",
  "This repository uses oflow as its GitLab-first planning contract.",
  "Read `.oflow/WORKFLOW.md` before changing code and use the oflow CLI for",
  "planning context. The same contract is usable from GitHub Copilot, VS Code",
  "agents, Claude, Codex, CI jobs, and other terminal-capable agents.",
  "",
  "## Low-token context flow",
  "",
  "- Start with `oflow work --mine --refresh --json` and `oflow sync --summary --refresh --json`.",
  "- Use `oflow work --mine --cached --json` and `oflow sync --summary --cached --json` during exploration.",
  "- Use `oflow context --story <iid> --json` and `oflow assess --story <iid> --json` for focused evidence.",
  "- Refresh before any remote change; cached data is not remote truth.",
  "",
  "## Safety",
  "",
  "Remote planning writes must follow `plan -> approve -> apply -> verify`.",
  "Never put GitLab tokens in this repository, editor settings, prompts, or",
  "command-line arguments. Use `oflow auth login` or `--token-stdin`.",
  "",
  "The local dashboard is read-only and binds to 127.0.0.1. It never receives",
  "GitLab credentials. Run `oflow dashboard` for the local SQLite view.",
].join("\n") + "\n";

export function agentInstructionBlock(agent: AgentName): string {
  const name = agent === "claude" ? "Claude" : agent === "omp" ? "OMP" : "Codex";
  return [
    "<!-- oflow instructions for " + name + " -->",
    "This repository is managed by oflow. oflow is the workflow authority: REST, glab, GraphQL, and runtime-owned GitLab MCP are interchangeable execution transports for the operations oflow capabilities advertises. Configured MCP is not authenticated MCP; only oflow capabilities --probe reports a real write.",
    "Read .oflow/WORKFLOW.md before changing code. Follow this lifecycle:",
    "  1. Refresh: `oflow work --mine --refresh --json` and `oflow sync --summary --refresh --json`. If refresh fails, do not apply a remote mutation.",
    "  2. Select a story: `oflow start --json` or `oflow start --story <iid> --json`.",
    "  3. Explore locally: `oflow work --mine --cached --json`, `oflow sync --summary --cached --json`, `oflow context --story <iid> --json`, `oflow assess --story <iid> --json`, and `oflow capabilities --json`.",
    "     Optional, and currently returns nothing: `oflow assess --story <iid> --triage --json` would add a hint about how much of the story is verification work. It is withheld because it was measured at 75% false alarms on real story text, and no threshold placement fixes that. Do not rely on it, and do not set OFLOW_LAYA_TRIAGE_UNCALIBRATED to work around it.",
    "  4. Run repository verification checks. If workflow.verification.checks is declared, `oflow verify-local --json` records bounded, tree-bound evidence under .oflow/cache/ that `oflow check` and `oflow finish` consume.",
    "  5. Before claiming completion: `oflow verify --story <iid> --json`, then `oflow finish --story <iid> --json`. finish is read-only and reports readiness across acceptance criteria, merged MR, pipeline policy/evidence, clean Git, and repository verification.",
    "  6. Only when finish.ready=true may the agent create, approve, apply, and verify the guarded close plan: `oflow plan issue update --story <iid> --state closed`, `oflow approve <plan>`, `oflow apply <plan>`, `oflow verify --plan <plan>`.",
    "  7. Refresh again after every remote change and emit oflow handoff --story <iid> --json for the next agent.",
    "Cache policy: --cached reads are offline and never contact GitLab; they reuse the actor identity recorded by the last live refresh. Cached assigned-work reads require a fresh identity; run oflow work --mine --refresh whenever the GitLab identity changes.",
    "Safety: never place a token in the repository; use oflow auth login or --token-stdin. If a capability is missing, oflow doctor --check-api --json names the oflow-level mitigation. workflow.verification with policy:required will block oflow finish when stale or missing.",
    "Delegated MCP scope: merge_request.create only. Direct REST/glab backends carry MR create/update and other issue writes; git push -o merge_request.create is a separate Git transport fallback, not MCP.",
  ].join("\n");
}

/**
 * Managed bridge for OMP's native project context path. Small by design:
 * `.oflow/WORKFLOW.md` stays the single source of truth; everything else is
 * a bridge to it.
 */
export const OMP_AGENTS_BRIDGE_MARKDOWN = [
  "# oflow project workflow",
  "",
  "This repository uses oflow.",
  "",
  "Before choosing or changing GitLab work:",
  "1. Read `.oflow/WORKFLOW.md`.",
  "2. Run `oflow start --json` or the smallest relevant oflow command.",
  "3. Prefer cached oflow context during repeated exploration.",
  "4. Refresh before remote mutations.",
  "5. Do not bypass oflow approval/policy gates for workflow-changing GitLab actions.",
  "6. After remote actions, run the required oflow verification/refresh step.",
  "",
  "GitLab MCP, glab, REST, and GraphQL are execution transports.",
  "`.oflow/WORKFLOW.md` is the workflow authority.",
].join("\n") + "\n";

export function ompCommandMarkdown(command: "start" | "status" | "verify" | "handoff"): string {
  const bodies: Record<typeof command, string[]> = {
    start: [
      "---",
      "description: Start or continue the correct oflow-managed work",
      "---",
      "",
      "Read `.oflow/WORKFLOW.md`.",
      "",
      "Run:",
      "",
      "`oflow start --json`",
      "",
      "Use the returned work item, constraints, acceptance criteria, evidence,",
      "and policy as the authoritative workflow context.",
      "",
      "Use available GitLab MCP tools only when the action is allowed by the",
      "returned policy. Do not bypass an oflow approval requirement.",
    ],
    status: [
      "---",
      "description: Summarize the current oflow project and story state",
      "---",
      "",
      "Run:",
      "",
      "`oflow sync --summary --cached --json`",
      "",
      "If the snapshot is stale or missing, run `oflow sync --summary --refresh --json`.",
      "Report project, iteration, and story progress concisely.",
    ],
    verify: [
      "---",
      "description: Verify acceptance evidence and delivery state for the active story",
      "---",
      "",
      "Run:",
      "",
      "`oflow assess --story <iid> --json`",
      "",
      "For remote delivery verification, run `oflow verify --story <iid>`.",
      "Do not report a criterion as satisfied without explicit evidence.",
    ],
    handoff: [
      "---",
      "description: Produce a compact handoff for the next agent session",
      "---",
      "",
      "Run:",
      "",
      "`oflow sync --summary --refresh --json`",
      "",
      "Summarize the active story, acceptance criteria status, evidence, MR and",
      "pipeline state, and the next required action so the next agent can",
      "continue without reconstructing history.",
    ],
  };
  return bodies[command].join("\n") + "\n";
}
