import type { AgentName } from "./types.js";

export const WORKFLOW_MARKER = "OFLOW MANAGED BLOCK";
export const CACHE_POLICY_MARKER = "OFLOW CACHE POLICY";

export const CACHE_POLICY_MARKDOWN = [
  "## Mandatory cache policy",
  "",
  "Agents must follow this refresh policy:",
  "",
  "1. At the start of a work session, run `oflow work --mine --refresh --json` and `oflow sync --summary --refresh --json`.",
  "2. During exploration and repeated context reads, use `oflow work --mine --cached --json` and `oflow sync --summary --cached --json`.",
  "3. Before planning, approving, applying, or verifying a remote GitLab change, refresh current state; never treat cached data as remote truth.",
  "4. If refresh fails, continue local analysis only and do not apply a remote mutation.",
  "5. After applying a remote change, refresh the work and project snapshots again.",
  "6. Use `oflow context --story <iid>` and `oflow assess --story <iid> --json` for detailed story and acceptance-criteria evidence.",
  "7. Use `oflow dashboard` for a local read-only view; it binds to 127.0.0.1 and never receives GitLab credentials.",
  "",
  "Cached reads never contact GitLab. They are a local read model, not a freshness guarantee.",
].join("\n");

const CACHE_POLICY_MANAGED_BLOCK = [
  "<!-- BEGIN " + CACHE_POLICY_MARKER + " -->",
  CACHE_POLICY_MARKDOWN,
  "<!-- END " + CACHE_POLICY_MARKER + " -->",
].join("\n");

export const WORKFLOW_MARKDOWN = [
  "# oflow workflow",
  "",
  "This project uses oflow as its GitLab-first agent workflow contract.",
  "",
  "## Before starting",
  "",
  "1. Read this file, the story context, and the relevant local code.",
  "2. If no story is known, run oflow work to inspect open GitLab work items.",
  "3. Resolve the active story with oflow start --story <iid> or the branch naming convention.",
  "4. Run oflow context --story <iid> and preserve the story's acceptance criterion IDs.",
  "5. If GitLab access is missing, run oflow auth login; never put tokens in this repository. During setup or troubleshooting, use oflow doctor --check-api --json for bounded read diagnostics; it never probes writes.",
  "6. When asked to sync project state, run oflow sync --summary --json for the token-light overview. Use oflow sync --json only when full bounded planning collections or pagination are needed. Use oflow sync --cached --summary --json for repeated context when the last snapshot is acceptable, and --refresh when current GitLab state is required. For repeated assigned-work context, use oflow work --mine --cached after an initial oflow work --mine --refresh; cached reads never contact GitLab. Add --epics only when group-level epic context is needed; it costs one extra bounded GraphQL read. When assessing one story, run oflow assess --story <iid> --json and use oflow capabilities --json to discover supported operations.",
  "8. State the plan and identify anything ambiguous before making code changes.",
  "",
  CACHE_POLICY_MANAGED_BLOCK,
  "",
  "## While working",
  "",
  "- Treat the GitLab story and its acceptance criteria as the source of truth.",
  "- Do not silently change acceptance criteria; ask the user or record the clarification in GitLab.",
  "- Keep implementation, tests, and documentation aligned.",
  "- Keep secrets and local .oflow/state/ files out of commits.",
  "- Refresh context when the story, MR, pipeline, or user direction changes.",
  "- Treat oflow sync as evidence collection; do not infer completion without concrete local or GitLab evidence.",
  "- In assess JSON, localReferences are advisory pointers only; inspect the referenced code/test and never treat an ID match as acceptance proof.",
  "- Verify pipeline evidence belongs to the selected MR and matches its head SHA when GitLab provides one; a branch pipeline alone is not enough.",
  "- The dashboard is local-only. Its refresh control records a request; run `oflow sync --refresh` explicitly to contact GitLab.",
  "",
  "## Before handoff",
  "",
  "1. Update the MR description with one checklist item for every AC-n criterion.",
  "2. Add concrete, non-placeholder Evidence: for every checked criterion.",
  "3. Run the relevant tests and describe their result as evidence.",
  "4. Run oflow verify --story <iid>.",
  "5. Report changed files, checks run, remaining risks, and the GitLab links.",
  "",
  "## Safety",
  "",
  "Read-only context, sync, and verification commands may run automatically.",
  "Use work/sync filters (--label, --milestone, --iteration, --epic, --assignee,",
  "--author, --search, --updated-after, --updated-before, --limit) when a smaller server-side snapshot is enough.",
  "Treat pagination.hasNextPage as evidence that a bounded collection needs a narrower filter or a larger limit.",
  "oflow does not configure or invoke MCP servers. Use plan assess --story <iid> --assignee <username> --milestone <title> when the assessment has a confirmed owner/timebox, or use plan issue update (including",
  "--labels for replacement or --add-labels/--remove-labels to preserve unrelated labels,",
  "--assignee username or --epic <id|none> or --iteration <title|iid|none>), plan issues labels --stories <iid,...> for",
  "bounded multi-story label changes, plan issues update --stories <iid,...> for",
  "bounded owner/timebox or --iteration changes, plan issue create/note, or",
  "plan label/milestone/board/board-list create/update, then approve, apply, and verify for supported writes. Do not",
  "use planned commands until oflow capabilities reports them as supported.",
].join("\n");

export const OFLOW_README_MARKDOWN = [
  "# .oflow",
  "",
  "This directory is the project-local configuration for oflow.",
  "",
  "- config.json records the GitLab remote and detected agent mode.",
  "- WORKFLOW.md is the shared agent workflow contract.",
  "- templates/merge-request.md is the acceptance-aware MR template.",
  "- GitLab credentials live outside the repository; use oflow auth login.",
  "- oflow reads GitLab through its typed REST API; explicit group-epic reads use GraphQL, while glab and MCP remain optional integrations.",
  "- oflow glab api is an explicit GET-only fallback for unwrapped endpoints.",
  "- Use work/sync filters, --limit, and sync --stale-days when an explicit age threshold is useful to keep planning context focused.",
  "- Live sync and work reads write credential-free ignored caches; sync --cached and work --cached never contact GitLab and report snapshot age. Refresh before relying on current state or preparing a remote write.",
  "- Mandatory cache policy: refresh at session start, use cached reads during exploration, refresh before remote changes, stop remote mutations if refresh fails, and refresh again after applying changes.",
  "- In sync JSON, check pagination.hasNextPage before treating a collection as complete.",
  "- Use oflow audit --json to inspect local plan lifecycle history; it never contacts GitLab or contains tokens.",
  "- Use plan issues labels --stories <iid,...> for bounded multi-story workflow-label changes.",
  "- Use oflow audit --json to review local plan lifecycle history without contacting GitLab.",
  "- state/ and cache/ are local and ignored; cache/oflow.db is the local SQLite read model and may contain project context but never credentials.",
  "- oflow doctor --check-api --json reports bounded REST/GraphQL read probes, optional backend status, and write capabilities as not-probed; it never mutates GitLab.",
  "- Scrum/planning: work items, acceptance criteria, labels, boards, milestones, iterations, group epics, MRs, and pipelines.",
  "- GitHub Copilot and VS Code agents can use .github/copilot-instructions.md and this same CLI JSON contract.",
  "- Run oflow cache status --json for local cache age/schema/invalidation diagnostics, and oflow dashboard for the loopback-only browser view.",
  "",
    "Run oflow doctor --check-api --json to inspect setup and bounded API access, oflow sync",
    "--summary --json for a token-light overview, oflow sync --json for the full bounded snapshot, oflow sync --cached --json for a no-network repeat read, oflow iteration --state current --json for a focused sprint view, oflow cadence --json for the optional parent-group cadence, or oflow assess --story <iid> --json for",
  "compact progress evidence for one story.",
].join("\n");

export const MERGE_REQUEST_TEMPLATE_MARKDOWN = [
  "# Summary",
  "",
  "## Story",
  "",
  "Closes #<story-iid>",
  "",
  "## Acceptance criteria verification",
  "",
  "- [ ] AC-1: <copy the exact criterion text>",
  "  Evidence: TBD",
  "",
  "<Repeat one checked item and one concrete Evidence: line for every criterion.>",
  "",
  "## Implementation notes",
  "",
  "- What changed?",
  "- What tests or other verification were run?",
  "- What remains or needs follow-up?",
].join("\n");

export const COPILOT_INSTRUCTIONS_MARKDOWN = [
  "# oflow instructions for GitHub Copilot and VS Code agents",
  "",
  "This repository uses oflow as its GitLab-first planning contract.",
  "Read `.oflow/WORKFLOW.md` before changing code and use the oflow CLI for",
  "planning context. The same contract is usable from GitHub Copilot, VS Code",
  "agents, Claude, Codex, CI jobs, and other terminal-capable agents.",
  "",
  "## Low-token context flow",
  "",
  "- Start with `oflow work --mine --refresh --json` and `oflow sync --summary --refresh --json`.",
  "- Use `oflow work --mine --cached --json` and `oflow sync --summary --cached --json` during exploration.",
  "- Use `oflow context --story <iid> --json` and `oflow assess --story <iid> --json` for focused evidence.",
  "- Refresh before any remote change; cached data is not remote truth.",
  "",
  "## Safety",
  "",
  "Remote planning writes must follow `plan -> approve -> apply -> verify`.",
  "Never put GitLab tokens in this repository, editor settings, prompts, or",
  "command-line arguments. Use `oflow auth login` or `--token-stdin`.",
  "",
  "The local dashboard is read-only and binds to 127.0.0.1. It never receives",
  "GitLab credentials. Run `oflow dashboard` for the local SQLite view.",
].join("\n") + "\n";

export function agentInstructionBlock(agent: AgentName): string {
  const name = agent === "claude" ? "Claude" : "Codex";
  return [
    "<!-- oflow instructions for " + name + " -->",
    "This repository is managed by oflow. Read .oflow/WORKFLOW.md before changing code.",
    "Mandatory cache policy: at session start run oflow work --mine --refresh and",
    "oflow sync --summary --refresh; use --cached reads during exploration; refresh",
    "before planning/approving/applying/verifying remote changes; if refresh fails,",
    "do not apply a remote mutation; refresh again after applying changes. Use oflow",
    "work --mine --cached for repeated assigned-work context; cached data is never",
    "remote truth. Use oflow work for other current stories, then use oflow context --story <iid>",
    "to load the selected story and acceptance criteria. When asked to sync progress,",
    "use oflow sync --summary --json for project state (use --cached for an acceptable local snapshot, --refresh when current GitLab state is required; use sync --json only for full bounded collections; add --epics for group epics), oflow iteration --state current --json for a focused sprint view, oflow assess --story <iid> --json",
    "for story progress, oflow mr --iid <iid> --json for compact MR status, and",
    "oflow capabilities --json. If API",
    "access is missing, use oflow auth login; never place a token in the repository.",
    "The local dashboard is read-only; use oflow dashboard for the SQLite view and",
    "run oflow sync --refresh explicitly when a remote refresh is required.",
    "Preserve AC-n identifiers, classify evidence conservatively, include Evidence:",
    "in the merge request, and run oflow verify --story <iid> before handoff. Use",
    "oflow epic --iid <iid> for group hierarchy, oflow iteration --group --state current --json when group sprint access is available, and use oflow plan assess --story <iid> or plan issues labels/update --stories <iid,...> or plan issue update --iteration <title|iid|none> or plan issues update --stories <iid,...> --iteration <title|iid|none>, plan issue update/note, label/milestone/board/board-list create/update followed by",
    "approve/apply/verify for supported writes; do not make other remote planning",
    "changes without an explicit supported plan.",
  ].join("\n");
}
